### ISSUE TITLE
Data/methods

### ISSUE THREAD

**Issue by bensoltoff** [css-research/fp-dailing616#2]
@dailing616 where is your data/methods section?

**Comment by dailing616** [comment]
Sorry I just noticed that I uploaded the file but didn't create a pull request for it. Would you mind regrading my assignment please? I sincerely apologize again for the mistake.

**Comment by bensoltoff** [comment]
I'll get to it when I have the chance. In the future, push all commits directly to `css-research/fp-dailing616`. You don't need to fork this repo since you have read/write access
